SRC_LIBMPI += \
	src/mpi/f/mpi_abort.c \
	src/mpi/f/mpi_address.c \
	src/mpi/f/mpi_allgather.c \
	src/mpi/f/mpi_allgatherv.c \
	src/mpi/f/mpi_allreduce.c \
	src/mpi/f/mpi_alltoall.c \
	src/mpi/f/mpi_alltoallv.c \
	src/mpi/f/mpi_attr_delete.c \
	src/mpi/f/mpi_attr_get.c \
	src/mpi/f/mpi_attr_put.c \
	src/mpi/f/mpi_barrier.c \
	src/mpi/f/mpi_bcast.c \
	src/mpi/f/mpi_bsend.c \
	src/mpi/f/mpi_bsend_init.c \
	src/mpi/f/mpi_buffer_attach.c \
	src/mpi/f/mpi_buffer_detach.c \
	src/mpi/f/mpi_cancel.c \
	src/mpi/f/mpi_cart_coords.c \
	src/mpi/f/mpi_cart_create.c \
	src/mpi/f/mpi_cart_get.c \
	src/mpi/f/mpi_cart_map.c \
	src/mpi/f/mpi_cart_rank.c \
	src/mpi/f/mpi_cart_shift.c \
	src/mpi/f/mpi_cart_sub.c \
	src/mpi/f/mpi_cartdim_get.c \
	src/mpi/f/mpi_comm_compare.c \
	src/mpi/f/mpi_comm_create.c \
	src/mpi/f/mpi_comm_dup.c \
	src/mpi/f/mpi_comm_free.c \
	src/mpi/f/mpi_comm_group.c \
	src/mpi/f/mpi_comm_rank.c \
	src/mpi/f/mpi_comm_remote_group.c \
	src/mpi/f/mpi_comm_remote_size.c \
	src/mpi/f/mpi_comm_size.c \
	src/mpi/f/mpi_comm_split.c \
	src/mpi/f/mpi_comm_test_inter.c \
	src/mpi/f/mpi_dims_create.c \
	src/mpi/f/mpi_errhandler_create.c \
	src/mpi/f/mpi_errhandler_free.c \
	src/mpi/f/mpi_errhandler_get.c \
	src/mpi/f/mpi_errhandler_set.c \
	src/mpi/f/mpi_error_class.c \
	src/mpi/f/mpi_error_string.c \
	src/mpi/f/mpi_finalize.c \
	src/mpi/f/mpi_finalized.c \
	src/mpi/f/mpi_gather.c \
	src/mpi/f/mpi_gatherv.c \
	src/mpi/f/mpi_get_count.c \
	src/mpi/f/mpi_get_elements.c \
	src/mpi/f/mpi_get_processor_name.c \
	src/mpi/f/mpi_get_version.c \
	src/mpi/f/mpi_graph_create.c \
	src/mpi/f/mpi_graph_get.c \
	src/mpi/f/mpi_graph_map.c \
	src/mpi/f/mpi_graph_neighbors.c \
	src/mpi/f/mpi_graph_neighbors_count.c \
	src/mpi/f/mpi_graphdims_get.c \
	src/mpi/f/mpi_group_compare.c \
	src/mpi/f/mpi_group_difference.c \
	src/mpi/f/mpi_group_excl.c \
	src/mpi/f/mpi_group_free.c \
	src/mpi/f/mpi_group_incl.c \
	src/mpi/f/mpi_group_intersection.c \
	src/mpi/f/mpi_group_range_excl.c \
	src/mpi/f/mpi_group_range_incl.c \
	src/mpi/f/mpi_group_rank.c \
	src/mpi/f/mpi_group_size.c \
	src/mpi/f/mpi_group_translate_ranks.c \
	src/mpi/f/mpi_group_union.c \
	src/mpi/f/mpi_ibsend.c \
	src/mpi/f/mpi_init.c \
	src/mpi/f/mpi_initialized.c \
	src/mpi/f/mpi_intercomm_create.c \
	src/mpi/f/mpi_intercomm_merge.c \
	src/mpi/f/mpi_iprobe.c \
	src/mpi/f/mpi_irecv.c \
	src/mpi/f/mpi_irsend.c \
	src/mpi/f/mpi_isend.c \
	src/mpi/f/mpi_issend.c \
	src/mpi/f/mpi_keyval_create.c \
	src/mpi/f/mpi_keyval_free.c \
	src/mpi/f/mpi_op_create.c \
	src/mpi/f/mpi_op_free.c \
	src/mpi/f/mpi_pack.c \
	src/mpi/f/mpi_pack_size.c \
	src/mpi/f/mpi_pcontrol.c \
	src/mpi/f/mpi_probe.c \
	src/mpi/f/mpi_recv.c \
	src/mpi/f/mpi_recv_init.c \
	src/mpi/f/mpi_reduce.c \
	src/mpi/f/mpi_reduce_scatter.c \
	src/mpi/f/mpi_request_free.c \
	src/mpi/f/mpi_rsend.c \
	src/mpi/f/mpi_rsend_init.c \
	src/mpi/f/mpi_scan.c \
	src/mpi/f/mpi_scatter.c \
	src/mpi/f/mpi_scatterv.c \
	src/mpi/f/mpi_send.c \
	src/mpi/f/mpi_send_init.c \
	src/mpi/f/mpi_sendrecv.c \
	src/mpi/f/mpi_sendrecv_replace.c \
	src/mpi/f/mpi_ssend.c \
	src/mpi/f/mpi_ssend_init.c \
	src/mpi/f/mpi_start.c \
	src/mpi/f/mpi_startall.c \
	src/mpi/f/mpi_test_cancelled.c \
	src/mpi/f/mpi_test.c \
	src/mpi/f/mpi_testall.c \
	src/mpi/f/mpi_testany.c \
	src/mpi/f/mpi_testsome.c \
	src/mpi/f/mpi_topo_test.c \
	src/mpi/f/mpi_type_commit.c \
	src/mpi/f/mpi_type_contiguous.c \
	src/mpi/f/mpi_type_extent.c \
	src/mpi/f/mpi_type_free.c \
	src/mpi/f/mpi_type_get_contents.c \
	src/mpi/f/mpi_type_get_envelope.c \
	src/mpi/f/mpi_type_hindexed.c \
	src/mpi/f/mpi_type_hvector.c \
	src/mpi/f/mpi_type_indexed.c \
	src/mpi/f/mpi_type_lb.c \
	src/mpi/f/mpi_type_size.c \
	src/mpi/f/mpi_type_struct.c \
	src/mpi/f/mpi_type_ub.c \
	src/mpi/f/mpi_type_vector.c \
	src/mpi/f/mpi_unpack.c \
	src/mpi/f/mpi_wait.c \
	src/mpi/f/mpi_waitall.c \
	src/mpi/f/mpi_waitany.c \
	src/mpi/f/mpi_waitsome.c \
	src/mpi/f/mpi_wtick.c \
	src/mpi/f/mpi_wtime.c
