SRC_LIBMPI += \
	mpi/c/mpi_abort.c \
	mpi/c/mpi_address.c \
	mpi/c/mpi_allgather.c \
	mpi/c/mpi_allgatherv.c \
	mpi/c/mpi_allreduce.c \
	mpi/c/mpi_alltoall.c \
	mpi/c/mpi_alltoallv.c \
	mpi/c/mpi_alltoallw.c \
	mpi/c/mpi_attr_delete.c \
	mpi/c/mpi_attr_get.c \
	mpi/c/mpi_attr_put.c \
	mpi/c/mpi_barrier.c \
	mpi/c/mpi_bcast.c \
	mpi/c/mpi_bsend.c \
	mpi/c/mpi_bsend_init.c \
	mpi/c/mpi_buffer_attach.c \
	mpi/c/mpi_buffer_detach.c \
	mpi/c/mpi_cancel.c \
	mpi/c/mpi_cart_coords.c \
	mpi/c/mpi_cart_create.c \
	mpi/c/mpi_cartdim_get.c \
	mpi/c/mpi_cart_get.c \
	mpi/c/mpi_cart_map.c \
	mpi/c/mpi_cart_rank.c \
	mpi/c/mpi_cart_shift.c \
	mpi/c/mpi_cart_sub.c \
	mpi/c/mpi_comm_compare.c \
	mpi/c/mpi_comm_create.c \
	mpi/c/mpi_comm_dup.c \
	mpi/c/mpi_comm_free.c \
	mpi/c/mpi_comm_group.c \
	mpi/c/mpi_comm_rank.c \
	mpi/c/mpi_comm_remote_group.c \
	mpi/c/mpi_comm_remote_size.c \
	mpi/c/mpi_comm_size.c \
	mpi/c/mpi_comm_split.c \
	mpi/c/mpi_comm_test_inter.c \
	mpi/c/mpi_dims_create.c \
	mpi/c/mpi_errhandler_create.c \
	mpi/c/mpi_errhandler_free.c \
	mpi/c/mpi_errhandler_get.c \
	mpi/c/mpi_errhandler_set.c \
	mpi/c/mpi_error_class.c \
	mpi/c/mpi_error_string.c \
	mpi/c/mpi_finalize.c \
	mpi/c/mpi_finalized.c \
	mpi/c/mpi_gather.c \
	mpi/c/mpi_gatherv.c \
	mpi/c/mpi_get_count.c \
	mpi/c/mpi_get_elements.c \
	mpi/c/mpi_get_processor_name.c \
	mpi/c/mpi_get_version.c \
	mpi/c/mpi_graph_create.c \
	mpi/c/mpi_graphdims_get.c \
	mpi/c/mpi_graph_get.c \
	mpi/c/mpi_graph_map.c \
	mpi/c/mpi_graph_neighbors.c \
	mpi/c/mpi_graph_neighbors_count.c \
	mpi/c/mpi_group_compare.c \
	mpi/c/mpi_group_difference.c \
	mpi/c/mpi_group_excl.c \
	mpi/c/mpi_group_free.c \
	mpi/c/mpi_group_incl.c \
	mpi/c/mpi_group_intersection.c \
	mpi/c/mpi_group_range_excl.c \
	mpi/c/mpi_group_range_incl.c \
	mpi/c/mpi_group_rank.c \
	mpi/c/mpi_group_size.c \
	mpi/c/mpi_group_translate_ranks.c \
	mpi/c/mpi_group_union.c \
	mpi/c/mpi_ibsend.c \
	mpi/c/mpi_init.c \
	mpi/c/mpi_initialized.c \
	mpi/c/mpi_intercomm_create.c \
	mpi/c/mpi_intercomm_merge.c \
	mpi/c/mpi_iprobe.c \
	mpi/c/mpi_irecv.c \
	mpi/c/mpi_irsend.c \
	mpi/c/mpi_isend.c \
	mpi/c/mpi_issend.c \
	mpi/c/mpi_keyval_create.c \
	mpi/c/mpi_keyval_free.c \
	mpi/c/mpi_op_create.c \
	mpi/c/mpi_op_free.c \
	mpi/c/mpi_pack.c \
	mpi/c/mpi_pack_size.c \
	mpi/c/mpi_pcontrol.c \
	mpi/c/mpi_probe.c \
	mpi/c/mpi_recv.c \
	mpi/c/mpi_recv_init.c \
	mpi/c/mpi_reduce.c \
	mpi/c/mpi_reduce_scatter.c \
	mpi/c/mpi_request_free.c \
	mpi/c/mpi_rsend.c \
	mpi/c/mpi_rsend_init.c \
	mpi/c/mpi_scan.c \
	mpi/c/mpi_scatter.c \
	mpi/c/mpi_scatterv.c \
	mpi/c/mpi_send.c \
	mpi/c/mpi_send_init.c \
	mpi/c/mpi_sendrecv.c \
	mpi/c/mpi_sendrecv_replace.c \
	mpi/c/mpi_ssend.c \
	mpi/c/mpi_ssend_init.c \
	mpi/c/mpi_startall.c \
	mpi/c/mpi_start.c \
	mpi/c/mpi_testall.c \
	mpi/c/mpi_testany.c \
	mpi/c/mpi_test.c \
	mpi/c/mpi_test_cancelled.c \
	mpi/c/mpi_testsome.c \
	mpi/c/mpi_topo_test.c \
	mpi/c/mpi_type_commit.c \
	mpi/c/mpi_type_contiguous.c \
	mpi/c/mpi_type_extent.c \
	mpi/c/mpi_type_free.c \
	mpi/c/mpi_type_get_contents.c \
	mpi/c/mpi_type_get_envelope.c \
	mpi/c/mpi_type_hindexed.c \
	mpi/c/mpi_type_hvector.c \
	mpi/c/mpi_type_indexed.c \
	mpi/c/mpi_type_lb.c \
	mpi/c/mpi_type_size.c \
	mpi/c/mpi_type_struct.c \
	mpi/c/mpi_type_ub.c \
	mpi/c/mpi_type_vector.c \
	mpi/c/mpi_unpack.c \
	mpi/c/mpi_waitall.c \
	mpi/c/mpi_waitany.c \
	mpi/c/mpi_wait.c \
	mpi/c/mpi_waitsome.c \
	mpi/c/mpi_wtick.c \
	mpi/c/mpi_wtime.c
